# Generated by Django 4.2.1 on 2023-10-11 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="ToDoList", new_name="Category",),
        migrations.RenameModel(old_name="ToDoItem", new_name="Task",),
    ]
